### ISSUE TITLE
[4.1] virtualgamepads service fails to launch

### ISSUE THREAD

**Issue by optyfr** [recalbox/recalbox-os#1301]
Wondered why there was nothing at TCP 8080 then realized that virtual-gamepads server was not started... But if I start it manually by calling "/etc/init.d/S92virtualgamepads start" I get the following error...

Starting virtual-gamepads server
# /usr/node-virtual-gamepads/node_modules/ref/lib/ref.js:1455
  if (inspect.name === 'refinspect') {
             ^

TypeError: Cannot read property 'name' of undefined
    at overwriteInspect (/usr/node-virtual-gamepads/node_modules/ref/lib/ref.js:1455:14)
    at Object.<anonymous> (/usr/node-virtual-gamepads/node_modules/ref/lib/ref.js:1417:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/node-virtual-gamepads/lib/uinput_structs.js:4:11)

**Comment by robsdedude** [comment]
Seems to be caused by outdated node version.

https://github.com/TooTallNate/ref/issues/86

Updating the ref library could help. But I don't have access to 4.1 so I can't check.
