### ISSUE TITLE
Moonlight Crash with Gpio Driver

### ISSUE THREAD

**Issue by Androsyn31** [recalbox/recalbox-os#729]
Hello, when the gpio driver is loaded, Moonlight crash every time when launch games on ES interface
here the error code 

`Traceback (most recent call last):
  File "/var/jenkins_home/workspace/recalbox-rpi2/output/target/usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py", line 137, in <module>
    command = generators[system.config['emulator']].generate(system, args.rom, playersControllers)
  File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonlightGenerator.py", line 14, in generate
    config = moonlightControllers.writeControllersConfig(system, rom, playersControllers)
  File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonlightControllers.py", line 29, in writeControllersConfig
    playerConfig = generateControllerConfig(controller, controllers[controller])
  File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonlightControllers.py", line 59, in generateControllerConfig
    mlAxis = moonlightAxis[inputIdx]
KeyError: 'up'
`

**Comment by substring** [comment]
configgen problem on pads that don't have analog sticks mapped on

until it is patched, turn the GPIO driver off, reboot, and use a pad

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.0.0-beta5
