### ISSUE TITLE
[4.1.0] Kodi 16 Jarvis, segfault on music

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#842]
I don't manage to get my music working in kodi 16 without a kodi crash.
Seems the same than http://trac.kodi.tv/ticket/16609

(gdb) run --standalone -fs
Starting program: /usr/lib/kodi/kodi.bin --standalone -fs
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[New LWP 1536]
[New LWP 1560]
[LWP 1560 exited]

Program received signal SIGSEGV, Segmentation fault.
0x747beb7c in std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) () from /usr/lib/libstdc++.so.6
(gdb) bt
#0  0x747beb7c in std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) () from /usr/lib/libstdc++.so.6
#1  0x0040277c in std::_Rb_tree_iterator<std::pair<Field const, CVariant> > std::_Rb_tree<Field, std::pair<Field const, CVariant>, std::_Select1st<std::pair<Field const, CVariant> >, std::less<Field>, std::allocator<std::pair<Field const, CVariant> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<Field&&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<Field const, CVariant> >, std::piecewise_construct_t const&, std::tuple<Field&&>&&, std::tuple<>&&) ()
#2  0x00bc930c in DatabaseUtils::GetDatabaseResults(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<Field, std::allocator<Field> > const&, std::unique_ptr<dbiplus::Dataset, std::default_delete<dbiplus::Dataset> > const&, std::vector<std::map<Field, CVariant, std::less<Field>, std::allocator<std::pair<Field const, CVariant> > >, std::allocator<std::map<Field, CVariant, std::less<Field>, std::allocator<std::pair<Field const, CVariant> > > > >&) ()
#3  0x00c17604 in SortUtils::SortFromDataset(SortDescription const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<dbiplus::Dataset, std::default_delete<dbiplus::Dataset> > const&, std::vector<std::map<Field, CVariant, std::less<Field>, std::allocator<std::pair<Field const, CVariant> > >, std::allocator<std::map<Field, CVariant, std::less<Field>, std::allocator<std::pair<Field const, CVariant> > > > >&) ()
#4  0x00821134 in CMusicDatabase::GetAlbumsByWhere(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CDatabase::Filter const&, CFileItemList&, SortDescription const&, bool) ()
#5  0x00821a50 in CMusicDatabase::GetAlbumsNav(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&, int, int, CDatabase::Filter const&, SortDescription const&, bool) ()
#6  0x00cf6754 in XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(CFileItemList&) const ()
#7  0x00cf6310 in XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetChilds(CFileItemList&) ()
#8  0x006c9e14 in XFILE::CMusicDatabaseDirectory::GetDirectory(CURL const&, CFileItemList&) ()
#9  0x006a26b0 in XFILE::CDirectory::GetDirectory(CURL const&, CFileItemList&, XFILE::CDirectory::CHints const&, bool) ()
#10 0x006a5458 in XFILE::CDirectory::GetDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&, XFILE::CDirectory::CHints const&, bool) ()
#11 0x006a54cc in XFILE::CDirectory::GetDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool) ()
#12 0x006fcc74 in XFILE::CVirtualDirectory::GetDirectory(CURL const&, CFileItemList&, bool) ()
#13 0x009b604c in CGUIMediaWindow::GetDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&) ()
#14 0x00853614 in CGUIWindowMusicBase::GetDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&) ()
#15 0x0085a014 in CGUIWindowMusicNav::GetDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&) ()
#16 0x009b8430 in CGUIMediaWindow::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#17 0x00856098 in CGUIWindowMusicNav::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#18 0x009af104 in CGUIMediaWindow::Refresh(bool) ()
#19 0x009b5eb4 in CGUIMediaWindow::OnInitWindow() ()
#20 0x00853e0c in CGUIWindowMusicBase::OnInitWindow() ()
#21 0x004319f4 in CGUIWindow::OnMessage(CGUIMessage&) ()
#22 0x009b77e8 in CGUIMediaWindow::OnMessage(CGUIMessage&) ()
#23 0x00852584 in CGUIWindowMusicBase::OnMessage(CGUIMessage&) ()
#24 0x00855694 in CGUIWindowMusicNav::OnMessage(CGUIMessage&) ()
#25 0x0043b2b4 in CGUIWindowManager::ActivateWindow_Internal(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool) ()
#26 0x0043b7dc in CGUIWindowManager::ActivateWindow(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool) ()
#27 0x007594d4 in ?? ()
#28 0x00756c68 in CBuiltins::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#29 0x009dcdbc in CApplication::ExecuteXBMCAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<CGUIListItem> const&) ()
#30 0x009dd8d4 in CApplication::OnMessage(CGUIMessage&) ()
#31 0x00438820 in CGUIWindowManager::SendMessage(CGUIMessage&) ()
#32 0x004540f8 in CGUIAction::ExecuteActions(int, int, std::shared_ptr<CGUIListItem> const&) const ()
#33 0x004c6840 in CGUIButtonControl::OnClick() ()
#34 0x004c4e94 in CGUIButtonControl::OnAction(CAction const&) ()
#35 0x00430880 in CGUIWindow::OnAction(CAction const&) ()
#36 0x004374d8 in CGUIWindowManager::OnAction(CAction const&) const ()
#37 0x009db788 in CApplication::OnAction(CAction const&) ()
#38 0x0074620c in CInputManager::ProcessGamepad(int) ()
#39 0x00748620 in CInputManager::Process(int, float) ()
#40 0x009d1558 in CApplication::FrameMove(bool, bool) ()
#41 0x00a6b4cc in CXBApplicationEx::Run() ()
#42 0x00a70d0c in XBMC_Run ()
#43 0x0032138c in main ()
(gdb)

**Comment by nadenislamarre** [comment]
the http://trac.kodi.tv/ticket/16609 could be related to mariadb which is not our case (source irc #kodi)

**Comment by nadenislamarre** [comment]
the thing could be :
http://forum.kodi.tv/showthread.php?tid=235883
http://forum.odroid.com/viewtopic.php?f=62&t=20345

=> kodi + gcc5 ;-(
i'm doing some compilationt tests to check.

**Comment by nadenislamarre** [comment]
fixed by downgrading to gcc 4.9
